# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rapor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rapor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brapor.proto\x12\x05rapor\"0\n\x0cTarihAraligi\x12\x11\n\tbaslangic\x18\x01 \x01(\t\x12\r\n\x05\x62itis\x18\x02 \x01(\t\"F\n\x0cSaatlikKayit\x12\x0c\n\x04saat\x18\x01 \x01(\t\x12\x1a\n\x12ortalama_aktif_guc\x18\x02 \x01(\x01\x12\x0c\n\x04\x61\x64\x65t\x18\x03 \x01(\x05\"5\n\x0cSaatlikRapor\x12%\n\x08kayitlar\x18\x01 \x03(\x0b\x32\x13.rapor.SaatlikKayit2K\n\x0cRaporServisi\x12;\n\x0fSaatlikOrtalama\x12\x13.rapor.TarihAraligi\x1a\x13.rapor.SaatlikRaporb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rapor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TARIHARALIGI']._serialized_start=22
  _globals['_TARIHARALIGI']._serialized_end=70
  _globals['_SAATLIKKAYIT']._serialized_start=72
  _globals['_SAATLIKKAYIT']._serialized_end=142
  _globals['_SAATLIKRAPOR']._serialized_start=144
  _globals['_SAATLIKRAPOR']._serialized_end=197
  _globals['_RAPORSERVISI']._serialized_start=199
  _globals['_RAPORSERVISI']._serialized_end=274
# @@protoc_insertion_point(module_scope)
